# Generated by Django 3.2.9 on 2021-11-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
